In [19]:
import numpy as np

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('../Pengenalan/DS Dataset Mahir/smsspamcollection.tsv', sep='\t')

In [22]:
df.head(10)

label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2
5  spam  FreeMsg Hey there darling it's been 3 week's n...     147      8
6   ham  Even my brother is not like to speak with me. ...      77      2
7   ham  As per your request 'Melle Melle (Oru Minnamin...     160      6
8  spam  WINNER!! As a valued network customer you have...     157      6
9  spam  Had your mobile 11 months or more? U R entitle...     154      2

In [23]:
df.isnull().sum()

label      0
message    0
length     0
punct      0
dtype: int64

In [24]:
len(df)

5572

In [25]:
df['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [26]:
x = df[['length', 'punct']]
y = df['label']

In [28]:
#train test split
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [32]:
print(x_train.shape)

(3733, 2)


In [35]:
print(x_test.shape)

(1839, 2)


In [37]:
#logistic regression
from sklearn.linear_model import LogisticRegression

In [39]:
lr_model = LogisticRegression(solver='lbfgs')

In [41]:
lr_model.fit(x_train, y_train)

LogisticRegression()

In [44]:
from sklearn import metrics

In [46]:
prediction = lr_model.predict(x_test)

In [48]:
print(metrics.confusion_matrix(y_test, prediction))

[[1547   46]
 [ 241    5]]


In [50]:
print(metrics.classification_report(y_test, prediction))

              precision    recall  f1-score   support

         ham       0.87      0.97      0.92      1593
        spam       0.10      0.02      0.03       246

    accuracy                           0.84      1839
   macro avg       0.48      0.50      0.47      1839
weighted avg       0.76      0.84      0.80      1839



In [53]:
#print akurasi
print(metrics.accuracy_score(y_test, prediction))

0.843936922240348


In [58]:
from sklearn.naive_bayes import MultinomialNB
nb_model = MultinomialNB()

In [60]:
nb_model.fit(x_train, y_train)

MultinomialNB()

In [62]:
prediction = nb_model.predict(x_test)

In [64]:
print(metrics.confusion_matrix(y_test, prediction))
print(metrics.classification_report(y_test, prediction))
print(metrics.accuracy_score(y_test, prediction))

[[1583   10]
 [ 246    0]]
              precision    recall  f1-score   support

         ham       0.87      0.99      0.93      1593
        spam       0.00      0.00      0.00       246

    accuracy                           0.86      1839
   macro avg       0.43      0.50      0.46      1839
weighted avg       0.75      0.86      0.80      1839

0.8607939097335509


In [65]:
from sklearn.svm import SVC
svc_model = SVC(gamma='auto')
svc_model.fit(x_train,y_train)

SVC(gamma='auto')

In [67]:
prediction = svc_model.predict(x_test)

In [68]:
print(metrics.confusion_matrix(y_test, prediction))
print(metrics.classification_report(y_test, prediction))
print(metrics.accuracy_score(y_test, prediction))

[[1515   78]
 [ 131  115]]
              precision    recall  f1-score   support

         ham       0.92      0.95      0.94      1593
        spam       0.60      0.47      0.52       246

    accuracy                           0.89      1839
   macro avg       0.76      0.71      0.73      1839
weighted avg       0.88      0.89      0.88      1839

0.8863512778684067
